### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xiang90**
Interesting project. Have been following yc/hacker news for quite a while. Need to fill in my home page though...

### CODE REVIEW

**Comment by tvvocold** [comment]
Cool, btw, could you tell me what's you username in QingHuai.org plz?

**Comment by tvvocold** [comment]
hi,
Have you got my email?

**Comment by xiang90** [comment]
Yea... I found it in trash... Anyway I will update it tonight. Do you have a wechat or something?

**Comment by tvvocold** [comment]
I think Hangouts is better , just send the Hangouts invite to ya:)

**Comment by tvvocold** [comment]
hi,
Plz resolve the conflicts , then choose your favorite tag like http://1.qinghuai.org/t/coreos

**Comment by tvvocold** [comment]
ping @xiang90 : )

**Pull request closed without merging**
